---
- block:
    - name: Updating Homebrew
      homebrew:
        update_homebrew: true
      when: homebrew_check.stat.exists

    - name: Upgrading Homebrew packages
      homebrew:
        upgrade_all: "{{ upgrade_homebrew_packages }}"
      register: result
      until: result is successful
      when: homebrew_check.stat.exists

    - name: Installing Homebrew cask packages
      homebrew_cask:
        name: "{{ item }}"
        state: present
      loop: "{{ brew_cask_packages }}"
      register: result
      until: result is successful
      when: homebrew_check.stat.exists

    - name: Installing Homebrew packages
      homebrew_cask:
        name: "{{ item }}"
        state: present
      loop: "{{ brew_packages }}"
      register: result
      until: result is successful
      when: homebrew_check.stat.exists
